Repository bcgov/gwells, pull requests merged in 2019-04, with the labels that each got.

#1252 Countable/milestone1
  app/backend/aquifers/fixtures/aquifers.json
  app/backend/aquifers/migrations/0010_aquifer_resource_sections.json
  app/backend/aquifers/migrations/0010_aquifer_resources.json
  app/backend/aquifers/migrations/0010_auto_20190307_2131.py
  app/backend/aquifers/migrations/0011_auto_20190309_0017.py
  app/backend/aquifers/migrations/0012_merge_20190313_1742.py
  app/backend/aquifers/migrations/0013_merge_20190313_1801.py
  app/backend/aquifers/migrations/0014_auto_20190315_0502.py
  app/backend/aquifers/migrations/0015_auto_20190315_0508.py
  app/backend/aquifers/migrations/0016_aquiferresourcesection_description.py
  app/backend/aquifers/models.py
  app/backend/aquifers/serializers.py
  app/backend/aquifers/urls.py
  app/backend/aquifers/views.py
  app/backend/gwells/codes.py
  app/backend/gwells/static/gwells/css/main.css
  app/frontend/src/aquifers/components/AquiferMap.vue
  app/frontend/src/aquifers/components/Form.vue
  app/frontend/src/aquifers/components/New.vue
  app/frontend/src/aquifers/components/Search.vue
  app/frontend/src/aquifers/components/View.vue
  app/frontend/src/aquifers/store/codes.js
  app/frontend/src/router.js
  app/frontend/test/unit/specs/aquifers/components/Search.spec.js
  app/frontend/test/unit/specs/aquifers/components/View.spec.js
  app/frontend/test/unit/specs/aquifers/components/__snapshots__/Search.spec.js.snap
  app/frontend/test/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
  app/scripts/download-aquifer-pdfs.py
  docker-compose.yml
  openshift/docker/minio/Dockerfile
  openshift/docker/minio/minio-entrypoint.sh
  tests/api-tests/aquifers_api_tests.json
  tests/functional-tests/src/test/groovy/pages/app/AquifersSearchPage.groovy
Labels: ready to merge

#1275 Sybrand/fix migration issue
  app/backend/aquifers/migrations/0011_auto_20190309_0017.py
  app/backend/aquifers/migrations/0014_auto_20190315_0502.py
  app/backend/aquifers/migrations/0015_auto_20190315_0502.py
  app/backend/aquifers/migrations/0016_auto_20190315_0508.py
  app/backend/aquifers/migrations/0017_aquiferresourcesection_description.py
  app/backend/registries/migrations/0014_auto_20190308_2348.py
  app/backend/registries/migrations/0015_auto_20190309_0017.py
  app/backend/submissions/migrations/0005_auto_20190309_0017.py
  app/backend/wells/migrations/0065_auto_20190309_0017.py
  app/backend/wells/migrations/0067_geom_updates.py
Labels: ready to merge

#1301 Fix merge conflict
  app/backend/wells/migrations/0072_merge_20190410_2303.py
Labels: ready to merge, shotgun

#1297 Submission Array Change Detection Fix
  app/frontend/src/submissions/components/SubmissionForm/Casings.vue
  app/frontend/src/submissions/components/SubmissionForm/ClosureDescription.vue
  app/frontend/src/submissions/components/SubmissionForm/Liner.vue
  app/frontend/src/submissions/components/SubmissionForm/Lithology.vue
  app/frontend/src/submissions/components/SubmissionForm/Screens.vue
  app/frontend/src/submissions/views/SubmissionsHome.vue
  app/frontend/test/unit/specs/submissions/ActivitySubmissionForm.spec.js
  app/frontend/test/unit/specs/submissions/Casings.spec.js
  app/frontend/test/unit/specs/submissions/ClosureDescription.spec.js
  app/frontend/test/unit/specs/submissions/Liner.spec.js
  app/frontend/test/unit/specs/submissions/Lithology.spec.js
  app/frontend/test/unit/specs/submissions/Screens.spec.js
Labels: ready to merge

#1296 [1777] remove submission id from submission history display
  app/frontend/src/submissions/components/SubmissionForm/SubmissionHistory.vue
  app/frontend/src/submissions/views/SubmissionDetail.vue
Labels: draft

#1253 [1552] Advanced search results
  app/backend/wells/filters.py
  app/backend/wells/views.py
  app/frontend/src/wells/components/AdvancedSearchFilter.vue
  app/frontend/src/wells/components/AdvancedSearchForm.vue
  app/frontend/src/wells/components/BasicSearchForm.vue
  app/frontend/src/wells/components/SearchColumnSelect.vue
  app/frontend/src/wells/components/SearchFormBooleanOrRange.vue
  app/frontend/src/wells/components/SearchFormBooleanOrText.vue
  app/frontend/src/wells/components/SearchFormInput.vue
  app/frontend/src/wells/components/SearchFormRadio.vue
  app/frontend/src/wells/components/SearchFormRange.vue
  app/frontend/src/wells/components/SearchFormSelect.vue
  app/frontend/src/wells/components/SearchMap.vue
  app/frontend/src/wells/components/SearchResultFilter.vue
  app/frontend/src/wells/components/SearchResults.vue
  app/frontend/src/wells/components/mixins/filters.js
  app/frontend/src/wells/searchFields.js
  app/frontend/src/wells/store/actions.types.js
  app/frontend/src/wells/store/index.js
  app/frontend/src/wells/store/mutations.types.js
  app/frontend/src/wells/views/WellSearch.vue
  app/frontend/test/unit/specs/wells/WellSearch.spec.js
  tests/api-tests/wells_search_api_tests.json
Labels: needs PO review
