Repository bcgov/gwells, pull requests merged in 2019-03, with the labels that each got.

#1197 Fix merge issues
  app/backend/gwells/migrations/0003_BCGW_ABMS_PROV.zip
  app/backend/gwells/migrations/0003_border.py
  app/backend/gwells/migrations/0011_merge_20190304_2344.py
  app/backend/gwells/migrations/0011_merge_20190305_0102.py
Labels: shotgun

#1098 [1530] simple well activity report history (starting point)
  Makefile
  app/backend/submissions/serializers.py
  app/backend/submissions/views.py
  app/backend/wells/admin.py
  app/backend/wells/models.py
  app/backend/wells/serializers.py
  app/backend/wells/stack.py
  app/backend/wells/urls.py
  app/backend/wells/views.py
  app/frontend/src/common/components/ChangeHistory.vue
  app/frontend/src/main.js
  app/frontend/src/router.js
  app/frontend/src/submissions/components/SubmissionForm/ActivitySubmissionForm.vue
  app/frontend/src/submissions/components/SubmissionForm/EditHistory.vue
  app/frontend/src/submissions/components/SubmissionForm/SubmissionHistory.vue
  app/frontend/src/submissions/router/index.js
  app/frontend/src/submissions/views/SubmissionDetail.vue
  app/frontend/src/submissions/views/SubmissionsHome.vue
  app/frontend/src/wells/views/WellDetail.vue
Labels: ready to merge

#1183 [1556] WIP: Advanced Search - Search Options
  app/backend/registries/views.py
  app/backend/submissions/serializers.py
  app/backend/submissions/views.py
  app/backend/wells/filters.py
  app/backend/wells/serializers.py
  app/backend/wells/views.py
  app/frontend/src/store/index.js
  app/frontend/src/wells/components/SearchFormInput.vue
  app/frontend/src/wells/components/SearchFormRadio.vue
  app/frontend/src/wells/components/SearchFormRange.vue
  app/frontend/src/wells/components/SearchFormSelect.vue
  app/frontend/src/wells/exports.js
  app/frontend/src/wells/searchFields.js
  app/frontend/src/wells/store/actions.types.js
  app/frontend/src/wells/store/index.js
  app/frontend/src/wells/store/mutations.types.js
  app/frontend/src/wells/views/WellSearch.vue
  tests/api-tests/wells_search_api_tests.json
Labels: draft

#1214 [1720] DataBC - server pre-rendered JSON
  Jenkinsfile
  app/backend/aquifers/tests.py
  app/backend/aquifers/views.py
  app/backend/gwells/management/commands/export_databc.py
  app/backend/gwells/models/common.py
  app/backend/gwells/tests/test_commands.py
  app/backend/registries/views.py
  app/backend/wells/management/commands/export.py
  app/backend/wells/tests/test_gis.py
  app/backend/wells/views.py
  openshift/export.cj.json
Labels: ready to merge

#1231 adjust bounding box filter
  app/backend/wells/filters.py
  app/backend/wells/views.py
Labels: draft

#1255 [1720] Spatial Layers
  Jenkinsfile
  app/backend/aquifers/apps.py
  app/backend/aquifers/fixtures/aquifers.json
  app/backend/aquifers/management/commands/__init__.py
  app/backend/aquifers/management/commands/import_bulk_shapefile.py
  app/backend/aquifers/models.py
  app/backend/aquifers/tests.py
  app/backend/aquifers/urls.py
  app/backend/aquifers/views.py
  app/backend/gwells/change_history.py
  app/backend/gwells/db_comments/__init__.py
  app/backend/gwells/db_comments/db_actions.py
  app/backend/gwells/db_comments/model_mixins.py
  app/backend/gwells/db_comments/patch_fields.py
  app/backend/gwells/fixtures/wellsearch.json
  app/backend/gwells/management/commands/export_databc.py
  app/backend/gwells/migrations/0006_auto_20190326_1914.py
  app/backend/gwells/models/__init__.py
  app/backend/gwells/models/common.py
  app/backend/gwells/models/lithology.py
  app/backend/gwells/models/screen.py
  app/backend/gwells/models/survey.py
  app/backend/gwells/open_api.py
  app/backend/registries/apps.py
  app/backend/registries/fixtures/registries-codetables.json
  app/backend/registries/fixtures/registries.json
  app/backend/registries/fixtures/registries_large.json
  app/backend/registries/migrations/0016_auto_20190326_1926.py
  app/backend/registries/migrations/0017_auto_20190326_1935.py
  app/backend/registries/models.py
  app/backend/registries/views.py
  app/backend/submissions/models.py
  app/backend/wells/apps.py
  app/backend/wells/migrations/0067_auto_20190326_1914.py
  app/backend/wells/migrations/0068_merge_20190328_2059.py
  app/backend/wells/models.py
  app/backend/wells/tests/test_gis.py
  app/backend/wells/urls.py
  app/backend/wells/views.py
  app/database/scripts/wellsearch/post-deploy.sql
  app/frontend/test/unit/specs/fakePerson.js
  app/frontend/test/unit/specs/fakeRegistration.js
  openshift/export.cj.json
  tests/api-tests/local_run_all.sh
  tests/api-tests/wells_search_api_tests.json
Labels: ready to merge
