Repository bcgov/gwells, pull requests merged in 2024-03, with the labels that each got.

#2179 [GWELLS-2175] TESTS** Add/Fix Postman Tests
  tests/api-tests/aquifers_api_tests.json
  tests/api-tests/registries_api_tests.json
  tests/api-tests/registries_v2_api_tests.json
  tests/api-tests/submissions_api_tests.json
  tests/api-tests/submissions_v2_api_tests.json
  tests/api-tests/wells_api_tests.json
  tests/api-tests/wells_search_api_tests.json
  tests/api-tests/wells_search_v2_api_tests.json
  tests/api-tests/wells_v2_api_tests.json
Labels: Testing

#2180 [GWELLS-2175] FIX** update tests to account for multi-field
  tests/api-tests/wells_search_api_tests.json
  tests/api-tests/wells_search_v2_api_tests.json
Labels: Testing

#2181 Revert "[GWELLS-2175] FIX** update tests to account for multi-field"
  tests/api-tests/wells_search_api_tests.json
  tests/api-tests/wells_search_v2_api_tests.json
Labels: Testing

#2182 Revert "[GWELLS-2175] TESTS** Add/Fix Postman Tests"
  tests/api-tests/aquifers_api_tests.json
  tests/api-tests/registries_api_tests.json
  tests/api-tests/registries_v2_api_tests.json
  tests/api-tests/submissions_api_tests.json
  tests/api-tests/submissions_v2_api_tests.json
  tests/api-tests/wells_api_tests.json
  tests/api-tests/wells_search_api_tests.json
  tests/api-tests/wells_search_v2_api_tests.json
  tests/api-tests/wells_v2_api_tests.json
Labels: Testing

#2109 [FEATURE] Code With Us QaQc Dashboard Dec 2023
  .gitignore
  app/backend/aquifers/fixtures/aquifers.json
  app/backend/gwells/fixtures/wellsearch.json
  app/backend/gwells/settings/__init__.py
  app/backend/gwells/utils.py
  app/backend/requirements.txt
  app/backend/wells/apps.py
  app/backend/wells/constants.py
  app/backend/wells/filters.py
  app/backend/wells/fixtures/qaqc_well_data.zip
  app/backend/wells/fixtures/well_detail_fixture.json
  app/backend/wells/migrations/0147_auto_20240105_qaqc.py
  app/backend/wells/migrations/0148_auto_20240105_qaqc_data.py
  app/backend/wells/models.py
  app/backend/wells/renderers.py
  app/backend/wells/serializers_v2.py
  app/backend/wells/signals.py
  app/backend/wells/urls.py
  app/backend/wells/utils.py
  app/backend/wells/views_v2.py
  app/frontend/package-lock.json
  app/frontend/src/common/components/Header.vue
  app/frontend/src/qaqc/components/QaQcExports.vue
  app/frontend/src/qaqc/components/QaQcFilters.vue
  app/frontend/src/qaqc/components/QaQcTable.vue
  app/frontend/src/qaqc/store/actions.types.js
  app/frontend/src/qaqc/store/index.js
  app/frontend/src/qaqc/store/mutations.types.js
  app/frontend/src/qaqc/store/triggers.types.js
  app/frontend/src/qaqc/views/QaQcDashboard.vue
  app/frontend/src/router.js
  app/frontend/src/store/index.js
  app/frontend/src/wells/components/mixins/filters.js
  app/scripts/qaqc/README.md
  app/scripts/qaqc/extract_data.py
  app/scripts/qaqc/get_esa_worldcover_bc.sh
  app/scripts/qaqc/gwells_locationqa.py
  app/scripts/qaqc/requirements.txt
Labels: Frontend, Backend, Scripts

#2194 [FEATURE][GWELLS-#2125] - Add the option to run docker-compose with the staging database
  .env
  .env.template
  .gitignore
  README.md
  app/scripts/backend-command-script.sh
  docker-compose.yml
Labels: Scripts, Docker

#2195 [FIX][CWU-QaQc]: Start and End Date Filter Fix for QaQc
  app/backend/wells/constants.py
  app/backend/wells/filters.py
  app/backend/wells/migrations/0148_auto_20240105_qaqc_data.py
  app/backend/wells/serializers_v2.py
Labels: Backend

#2196 [GWELLS-2177] TESTS** Increase Postman Testing coverage
  Jenkinsfile
  Jenkinsfile.ocp4
  tests/api-tests/aquifers_api_tests.json
  tests/api-tests/aquifers_v2_api_tests.json
  tests/api-tests/cities_api_tests.json
  tests/api-tests/configuration_api_tests.json
  tests/api-tests/exports_api_tests.json
  tests/api-tests/local_configurations.sh
  tests/api-tests/local_exports_utilities.sh
  tests/api-tests/local_wells_search.sh
  tests/api-tests/registries_api_tests.json
  tests/api-tests/registries_v2_api_tests.json
  tests/api-tests/submissions_api_tests.json
  tests/api-tests/submissions_v2_api_tests.json
  tests/api-tests/utilities_api_tests.json
  tests/api-tests/wells_api_tests.json
  tests/api-tests/wells_search_api_tests.json
  tests/api-tests/wells_search_v2_api_tests.json
  tests/api-tests/wells_v2_api_tests.json
Labels: Testing

#2200 [GWELLS-2177] TESTS** Removed Test Failing in Staging
  tests/api-tests/wells_api_tests.json
Labels: Testing

#2201 [GWELLS-2177] TESTS** Postman Test edits
  Jenkinsfile
  Jenkinsfile.ocp4
  tests/api-tests/aquifers_v2_api_tests.json
  tests/api-tests/wells_v2_api_tests.json
Labels: Testing

#2203 [GWELLS-2184] FEATURE** Remove Aquifer Parameter Halos from Well Search
  app/frontend/src/wells/components/SearchMap.vue
Labels: Frontend
